name: 'Sample React CI pipeline/workflow'

on: 
    push:
        branches:
            - main
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps: 
            - name: "Setup Node Js"
              uses: actions/setup-node@v6
              with:
                node-version: '21'
            
            - name: "Checking node version"
              run: node --version

            - name: "Clone the repository"
              uses: actions/checkout@v2

            - name: "list before installing node_modules"
              run: ls

            - name: "Install Dependecies"
              run: npm install
              
            - name: "List directories"
              run: ls
            
            - name: "Run Lint"
              run: npm run lint
              
            - name: "Run tests"
              run: npm test

            - name: "Run the build"
              run: npm run build
            
            - name: "Upload production-ready build files"
              uses: actions/upload-artifact@v6
              with: 
                name: build
                path: dist

